# Generated by Django 5.1.2 on 2024-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
